public GETDATE

EXTRN BUF0:BYTE
EXTRN YEAR:WORD,MONTH:WORD,DAY:WORD

DATASEG SEGMENT PARA 'mytitle'
	P DW ?  
DATASEG ENDS

CODESEG SEGMENT PARA 'code'
	ASSUME DS:DATASEG,CS:CODESEG

GET MACRO REG1,REG2,LOOPADDR
	LEA DI,REG1
	MOV AX,0
LOOPADDR:	MOV BL,[DI]
	        SUB BL,30H
	        MOV BH,0
	        MOV P,10
	        MUL P
	        ADD AX,BX
	        INC DI
	        LOOP LOOPADDR
	        MOV REG2,AX
ENDM
	
GETDATE PROC FAR
	PUSH DX
	PUSH AX
	PUSH BP
	MOV BP,SP
	
	MOV CX,2
	GET BUF0+2,MONTH,L1	;获得月份信息
	
	MOV CX,2
	GET BUF0+4,DAY,L2      ;获得日期信息
	
	MOV CX,4
	GET BUF0+6,YEAR,L3     ;获得年份信息
	
	POP DX
	POP AX
	POP BP
	RETF
	
GETDATE ENDP

CODESEG ENDS
END